volumes:
  node-red-data:
  grafana-data:
  influxdb-data:
  influxdb-config:

networks:
  trinity:

services:
  nodered:
    restart: unless-stopped
    image: nodered/node-red:2.2.2-12
    volumes:
    - node-red-data:/data
    networks:
      trinity:
        aliases:
        - nodered
    ports:
    - "1880:1880"

  influxdb:
    restart: unless-stopped
    image: influxdb:2.2.0-alpine
    volumes:
    - influxdb-data:/var/lib/influxdb2
    - influxdb-config:/etc/influxdb2
    environment:
    - DOCKER_INFLUXDB_INIT_MODE=setup
    - DOCKER_INFLUXDB_INIT_USERNAME=arduino
    - DOCKER_INFLUXDB_INIT_PASSWORD=x8trinity
    - DOCKER_INFLUXDB_INIT_ORG=arduino
    - DOCKER_INFLUXDB_INIT_BUCKET=x8-iot
    networks:
      trinity:
        aliases:
        - influxdb
    ports:
    - "8086:8086"

  grafana:
    restart: unless-stopped
    image: grafana/grafana:8.4.6
    volumes:
    - grafana-data:/var/lib/grafana
    networks:
      trinity:
        aliases:
        - grafana
    ports:
    - "3000:3000"
