version: "3.9"

volumes:
  node-red-data:
  grafana-data:
  influxdb-data:
  influxdb-config:

networks:
  trinity:

services:
  nodered:
    image: nodered/node-red
    volumes:
      - node-red-data:/data
    networks:
      trinity:
        aliases:
          - nodered
    ports:
      - "1880:1880"

  influxdb:
    image: influxdb:alpine
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=arduino
      - DOCKER_INFLUXDB_INIT_PASSWORD=x8trinity
      - DOCKER_INFLUXDB_INIT_ORG=arduino
      - DOCKER_INFLUXDB_INIT_BUCKET=x8-iot
    networks:
      trinity:
        aliases:
          - influxdb
    ports:
      - "8086:8086"

  grafana:
    image: grafana/grafana
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      trinity:
        aliases:
          - grafana
    ports:
      - "3000:3000"
