services:

  m4-rpc-proxy:
    image: hub.foundries.io/${FACTORY}/m4-rpc-proxy:latest
    restart: unless-stopped
    read_only: true
    user: "0"
    volumes:
    - "/tmp:/tmp"
    devices:
    - "/dev/x8h7_ui"
    - "/dev/ttyGS0"
    ports:
    - "5000-5100:5000-5100"
