version: '3.6'

services:
  xkiosk-firefox-browser:
    image: hub.foundries.io/${FACTORY}/x-kiosk-firefox:latest
    restart: always
    tty: true
    command: "google.com"
    network_mode: "host"
    tmpfs:
    - /run
    - /var/lock
    - /var/log
    - /tmp
    volumes:
    - /run/user/63:/run/user/63
    - /dev/dri:/dev/dri
    - /dev/galcore:/dev/galcore
    device_cgroup_rules:
    - 'c 199:* rmw'
    - 'c 226:* rmw'
