carrier_custom          1
is_on_carrier           yes
carrier_name            breakout
overlays                ov_som_lbee5kl1dx ov_som_x8h7 ov_carrier_breakout_gpio ov_carrier_breakout_i2s ov_carrier_breakout_sai ov_carrier_breakout_pdm ov_carrier_breakout_pwm ov_carrier_breakout_sdc ov_carrier_breakout_spdif ov_carrier_breakout_spi0 ov_carrier_breakout_spi1 ov_carrier_breakout_uart1 ov_carrier_breakout_uart3 ov_carrier_breakout_usbfs
