version: '3.6'

services:
  blob-opera:
    image: hub.foundries.io/${FACTORY}/blob-opera:latest
    restart: always
    tty: true
    command: "${ADDR-https://g.co/arts/9vQnmMqJvDx3LyAj6}"
    read_only: true
    user: "63"
    tmpfs:
    - /run
    - /var/lock
    - /var/log
    - /tmp
    volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
    - "/dev/snd"
