version: '3.6'

services:
  blob-opera:
    image: hub.foundries.io/arduino/blob-opera:latest
    restart: always
    tty: true
    command: "${ADDR-https://artsandculture.google.com/experiment/blob-opera}"
    read_only: true
    user: "63"
    tmpfs:
    - /run
    - /var/lock
    - /var/log
    - /tmp
    volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix
