services:
  python-weather-station:
    image: hub.foundries.io/${FACTORY}/python-weather-station:latest
    # image: python-weather-station:latest
    restart: unless-stopped
    environment:
    - PYTHONUNBUFFERED=1
    volumes:
    - /var/run/secrets:/app/config/
    extra_hosts:
    - "m4-proxy:host-gateway"
