#!/bin/bash

#LLVM
RUN ln -s /usr/bin/llvm-PerfectShuffle-13 /usr/bin/llvm-PerfectShuffle  
ln -s /usr/bin/llvm-addr2line-13 /usr/bin/llvm-addr2line  
ln -s /usr/bin/llvm-ar-13 /usr/bin/llvm-ar  
ln -s /usr/bin/llvm-as-13 /usr/bin/llvm-as  
ln -s /usr/bin/llvm-bcanalyzer-13 /usr/bin/llvm-bcanalyzer  
ln -s /usr/bin/llvm-bitcode-strip-13 /usr/bin/llvm-bitcode-strip  
ln -s /usr/bin/llvm-c-test-13 /usr/bin/llvm-c-test  
ln -s /usr/bin/llvm-cat-13 /usr/bin/llvm-cat  
ln -s /usr/bin/llvm-cfi-verify-13 /usr/bin/llvm-cfi-verify  
ln -s /usr/bin/llvm-config-13 /usr/bin/llvm-config  
ln -s /usr/bin/llvm-cov-13 /usr/bin/llvm-cov  
ln -s /usr/bin/llvm-cvtres-13 /usr/bin/llvm-cvtres  
ln -s /usr/bin/llvm-cxxdump-13 /usr/bin/llvm-cxxdump  
ln -s /usr/bin/llvm-cxxfilt-13 /usr/bin/llvm-cxxfilt  
ln -s /usr/bin/llvm-cxxmap-13 /usr/bin/llvm-cxxmap  
ln -s /usr/bin/llvm-diff-13 /usr/bin/llvm-diff  
ln -s /usr/bin/llvm-dis-13 /usr/bin/llvm-dis  
ln -s /usr/bin/llvm-dlltool-13 /usr/bin/llvm-dlltool  
ln -s /usr/bin/llvm-dwarfdump-13 /usr/bin/llvm-dwarfdump  
ln -s /usr/bin/llvm-dwp-13 /usr/bin/llvm-dwp  
ln -s /usr/bin/llvm-exegesis-13 /usr/bin/llvm-exegesis  
ln -s /usr/bin/llvm-extract-13 /usr/bin/llvm-extract  
ln -s /usr/bin/llvm-gsymutil-13 /usr/bin/llvm-gsymutil  
ln -s /usr/bin/llvm-ifs-13 /usr/bin/llvm-ifs  
ln -s /usr/bin/llvm-install-name-tool-13 /usr/bin/llvm-install-name-tool  
ln -s /usr/bin/llvm-jitlink-13 /usr/bin/llvm-jitlink  
ln -s /usr/bin/llvm-jitlink-executor-13 /usr/bin/llvm-jitlink-executor  
ln -s /usr/bin/llvm-lib-13 /usr/bin/llvm-lib  
ln -s /usr/bin/llvm-libtool-darwin-13 /usr/bin/llvm-libtool-darwin  
ln -s /usr/bin/llvm-link-13 /usr/bin/llvm-link  
ln -s /usr/bin/llvm-lipo-13 /usr/bin/llvm-lipo  
ln -s /usr/bin/llvm-lto-13 /usr/bin/llvm-lto  
ln -s /usr/bin/llvm-lto2-13 /usr/bin/llvm-lto2  
ln -s /usr/bin/llvm-mc-13 /usr/bin/llvm-mc  
ln -s /usr/bin/llvm-mca-13 /usr/bin/llvm-mca  
ln -s /usr/bin/llvm-ml-13 /usr/bin/llvm-ml  
ln -s /usr/bin/llvm-modextract-13 /usr/bin/llvm-modextract  
ln -s /usr/bin/llvm-mt-13 /usr/bin/llvm-mt  
ln -s /usr/bin/llvm-nm-13 /usr/bin/llvm-nm  
ln -s /usr/bin/llvm-objcopy-13 /usr/bin/llvm-objcopy  
ln -s /usr/bin/llvm-objdump-13 /usr/bin/llvm-objdump  
ln -s /usr/bin/llvm-opt-report-13 /usr/bin/llvm-opt-report  
ln -s /usr/bin/llvm-otool-13 /usr/bin/llvm-otool  
ln -s /usr/bin/llvm-pdbutil-13 /usr/bin/llvm-pdbutil  
ln -s /usr/bin/llvm-profdata-13 /usr/bin/llvm-profdata  
ln -s /usr/bin/llvm-profgen-13 /usr/bin/llvm-profgen  
ln -s /usr/bin/llvm-ranlib-13 /usr/bin/llvm-ranlib  
ln -s /usr/bin/llvm-rc-13 /usr/bin/llvm-rc  
ln -s /usr/bin/llvm-readelf-13 /usr/bin/llvm-readelf  
ln -s /usr/bin/llvm-readobj-13 /usr/bin/llvm-readobj  
ln -s /usr/bin/llvm-reduce-13 /usr/bin/llvm-reduce  
ln -s /usr/bin/llvm-rtdyld-13 /usr/bin/llvm-rtdyld  
ln -s /usr/bin/llvm-sim-13 /usr/bin/llvm-sim  
ln -s /usr/bin/llvm-size-13 /usr/bin/llvm-size  
ln -s /usr/bin/llvm-split-13 /usr/bin/llvm-split  
ln -s /usr/bin/llvm-stress-13 /usr/bin/llvm-stress  
ln -s /usr/bin/llvm-strings-13 /usr/bin/llvm-strings  
ln -s /usr/bin/llvm-strip-13 /usr/bin/llvm-strip  
ln -s /usr/bin/llvm-symbolizer-13 /usr/bin/llvm-symbolizer  
ln -s /usr/bin/llvm-tapi-diff-13 /usr/bin/llvm-tapi-diff  
ln -s /usr/bin/llvm-tblgen-13 /usr/bin/llvm-tblgen  
ln -s /usr/bin/llvm-undname-13 /usr/bin/llvm-undname  
ln -s /usr/bin/llvm-windres-13 /usr/bin/llvm-windres  
ln -s /usr/bin/llvm-xray-13 /usr/bin/llvm-xray
ln -s /usr/bin/clangd-13 /usr/bin/clangd
ln -s /usr/bin/clang-cpp-13 /usr/bin/clang-cpp
ln -s /usr/bin/clang-13 /usr/bin/clang
ln -s /usr/bin/clang++-13 /usr/bin/clang++
ln -s /usr/bin/lld-13 /usr/bin/lld
ln -s /usr/bin/lld-link-13 /usr/bin/lld-link
ln -s /usr/bin/lldb-13 /usr/bin/lldb
ln -s /usr/bin/lldb-argdumper-13 /usr/bin/lldb-argdumper
ln -s /usr/bin/lldb-instr-13 /usr/bin/lldb-instr
ln -s /usr/bin/lldb-server-13 /usr/bin/lldb-server
ln -s /usr/bin/lldb-vscode-13 /usr/bin/lldb-vscode
ln -s /usr/bin/ld.lld-13 /usr/bin/ld.lld

#GCC
ln -s /usr/bin/aarch64-linux-gnu-cpp-10 /usr/bin/aarch64-linux-gnu-cpp
ln -s /usr/bin/aarch64-linux-gnu-g++-10 /usr/bin/aarch64-linux-gnu-g++
ln -s /usr/bin/aarch64-linux-gnu-gcc-10 /usr/bin/aarch64-linux-gnu-gcc
ln -s /usr/bin/aarch64-linux-gnu-gcc-ar-10 /usr/bin/aarch64-linux-gnu-gcc-ar
ln -s /usr/bin/aarch64-linux-gnu-gcc-nm-10 /usr/bin/aarch64-linux-gnu-gcc-nm
ln -s /usr/bin/aarch64-linux-gnu-gcc-ranlib-10 /usr/bin/aarch64-linux-gnu-gcc-ranlib
ln -s /usr/bin/aarch64-linux-gnu-gcov-10 /usr/bin/aarch64-linux-gnu-gcov
ln -s /usr/bin/aarch64-linux-gnu-gcov-dump-10 /usr/bin/aarch64-linux-gnu-gcov-dump
ln -s /usr/bin/aarch64-linux-gnu-gcov-tool-10 /usr/bin/aarch64-linux-gnu-gcov-tool
ln -s /usr/bin/cpp-10 /usr/bin/cpp
ln -s /usr/bin/g++-10 /usr/bin/g++
ln -s /usr/bin/gcc-10 /usr/bin/gcc
ln -s /usr/bin/gcc-ar-10 /usr/bin/gcc-ar
ln -s /usr/bin/gcc-nm-10 /usr/bin/gcc-nm
ln -s /usr/bin/gcc-ranlib-10 /usr/bin/gcc-ranlib
ln -s /usr/bin/gcov-10 /usr/bin/gcov
ln -s /usr/bin/gcov-dump-10 /usr/bin/gcov-dump
ln -s /usr/bin/gcov-tool-10 /usr/bin/gcov-tool