version: '3.6'

services:
  aiot-cloud-provisioning:
    container_name: aiot-cloud-provisioning
    image: hub.foundries.io/${FACTORY}/aiot-cloud-provisioning:latest
    restart: unless-stopped
    tty: true
    read_only: false
    user: "0"
    environment:
      - 'DBUS_SYSTEM_BUS_ADDRESS=unix:path=/run/dbus/system_bus_socket'
    volumes:
      - '/run/dbus/system_bus_socket:/run/dbus/system_bus_socket'
      - '/run/arduino_hw_info.env:/run/arduino_hw_info.env:ro'
      - '/var:/var/secrets'
    devices:
      - '/dev/tee0'
