name: lora-node

services:

  lora-node-x8:
    container_name: lora-node
    image: hub.foundries.io/${FACTORY}/lora-node-x8:latest
    restart: unless-stopped
    environment:
    - PYTHONUNBUFFERED=1
    volumes:
    - '/var/run/secrets:/app/config/'
    - '/run/arduino_hw_info.env:/run/arduino_hw_info.env:ro'
    extra_hosts:
    - 'm4-proxy:host-gateway'
    devices:
    - '/dev/ttymxc3'
    - '/dev/gpiochip5'
    user: "0"
