name: arduino-ide-2

services:

  arduino-ide:
    image: arduino-ide-2:latest
    tmpfs:
    - /run
    - /var/lock
    - /var/log
    - /tmp
    volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix
    - /run/dbus:/run/dbus
