version: '3.6'

services:
  go-rpc-proxy:
    image: hub.foundries.io/${FACTORY}/go-rpc-proxy:latest
    restart: always
    tty: true
    read_only: true
    user: "0"
    volumes:
    - "/tmp:/tmp"
    devices:
    - "/dev/ttyGS0"
    ports:
    - "5002:5002"
    extra_hosts:
    - "m4-proxy:172.17.0.1"
