services:
  webapp:
    container_name: x8-webapp
    image: hub.foundries.io/${FACTORY}/arduino-ootb-webapp:latest
    #build: ../arduino-ootb-webapp
    restart: unless-stopped
    read_only: false
    user: "0"
    cap_add:
      - NET_ADMIN
    environment:
    - 'DBUS_SYSTEM_BUS_ADDRESS=unix:path=/run/dbus/system_bus_socket'
    - 'SSH_HOST=devel:22'
    - 'SSH_USER=root'
    - 'SSH_KEY=/root/.ssh/id_rsa'
    - 'SSH_KEY_PUB=/root/.ssh/id_rsa.pub'
    - 'LOG_LEVEL=1'
    - 'FACTORY_HARDWARE_ID=portenta-x8'
    - 'PROVISIONING_URL=x8-provisioning:1324'
    - 'IOT_SECRETS_PATH=/var/sota/iot-secrets.json'
    - 'UPDATE_JSON_URI=https://downloads.arduino.cc/portentax8image/info.json'
    - 'DOCKER_API_VERSION=1.41'
    ports:
    - '80:1323'
    volumes:
    - '/run/dbus/system_bus_socket:/run/dbus/system_bus_socket'
    - '/run/arduino_hw_info.env:/run/arduino_hw_info.env:ro'
    - '/var/sota:/var/sota'
    - '/etc/os-release:/etc/os-release:ro'
    - './keys:/tmp/keys:ro'
    - '/var/log:/var/log:ro'
    - '/dev/mmcblk2p2:/dev/mmcblk2p2:ro'
    - '/sys:/sys:ro'
    - '/var/run/docker.sock:/var/run/docker.sock:ro'

  devel:
    container_name: x8-devel
    hostname: "portenta-x8"
    image: hub.foundries.io/${FACTORY}/arduino-ootb-python-devel:latest
    #build: ../arduino-ootb-python-devel
    restart: unless-stopped
    tty: true
    read_only: false
    user: "0"
    environment:
    - 'COLUMNS=93'
    - 'ROWS=40'
    volumes:
    #- '/dev:/dev'
    - '/run/arduino_hw_info.env:/run/arduino_hw_info.env:ro'
    - '/etc/fw_env.config:/etc/fw_env.config:ro'
    - '/mnt/boot/uboot.env:/mnt/boot/uboot.env:rw'
    - '/sys/devices:/sys/devices'
    - '/sys/class/pwm:/sys/class/pwm'
    - '/sys/bus/iio:/sys/bus/iio'
    - '/var/sota:/var/sota'
    - './keys:/tmp/keys:ro'
    devices:
    - '/dev/i2c-3'
    - '/dev/i2c-2'
    - '/dev/i2c-1'
    #- '/dev/spidev0.0'
    - '/dev/gpiochip0'
    - '/dev/gpiochip1'
    - '/dev/gpiochip2'
    - '/dev/gpiochip3'
    - '/dev/gpiochip4'
    - '/dev/gpiochip5'
    - '/dev/tee0'

  provisioning:
    container_name: x8-provisioning
    image: hub.foundries.io/${FACTORY}/arduino-iot-cloud-provisioning:latest
    restart: unless-stopped
    tty: true
    read_only: false
    user: "0"
    environment:
    - 'DBUS_SYSTEM_BUS_ADDRESS=unix:path=/run/dbus/system_bus_socket'
    - 'IOT_API_URL=https://api2.arduino.cc'
    volumes:
    - '/run/dbus/system_bus_socket:/run/dbus/system_bus_socket'
    - '/run/arduino_hw_info.env:/run/arduino_hw_info.env:ro'
    - '/var/sota:/var/sota'
    devices:
    - '/dev/tee0'
