version: '3.6'

services:
  webapp:
    container_name: x8-setup
    image: hub.foundries.io/${FACTORY}/go-webapp-arduino:latest
    #build: ../go-webapp-arduino
    restart: unless-stopped
    read_only: false
    user: "0"
    cap_add:
      - NET_ADMIN
    environment:
      - 'DBUS_SYSTEM_BUS_ADDRESS=unix:path=/run/dbus/system_bus_socket'
      - 'SSH_HOST=devel:22'
      - 'SSH_USER=root'
      - 'SSH_KEY=/root/.ssh/id_rsa'
      - 'SSH_KEY_PUB=/root/.ssh/id_rsa.pub'
      - LOG_LEVEL=1
      - FACTORY_HARDWARE_ID=portenta-x8
    ports:
      - '80:1323'
    volumes:
      - '/run/dbus/system_bus_socket:/run/dbus/system_bus_socket'
      - '/run/arduino_hw_info.env:/run/arduino_hw_info.env:ro'
      - '/var/sota:/var/sota'
      - './keys:/tmp/keys:ro'

  devel:
    container_name: x8-devel
    hostname: "portenta-x8"
    image: hub.foundries.io/${FACTORY}/python-devel-arduino:latest
    #build: ../python-devel-arduino
    restart: unless-stopped
    tty: true
    read_only: false
    user: "0"
    volumes:
      #- '/dev:/dev'
      - '/run/arduino_hw_info.env:/run/arduino_hw_info.env:ro'
      - '/sys/devices:/sys/devices'
      - '/sys/class/pwm:/sys/class/pwm'
      - '/sys/bus/iio:/sys/bus/iio'
      - '/var/sota:/var/sota'
      - './keys:/tmp/keys:ro'
    devices:
      - '/dev/gpiochip5'
      - '/dev/tee0'

  provisioning:
    container_name: x8-provisioning
    image: hub.foundries.io/${FACTORY}/aiot-cloud-provisioning:latest
    restart: unless-stopped
    tty: true
    read_only: false
    user: "0"
    environment:
      - 'DBUS_SYSTEM_BUS_ADDRESS=unix:path=/run/dbus/system_bus_socket'
    volumes:
      - '/run/dbus/system_bus_socket:/run/dbus/system_bus_socket'
      - '/run/arduino_hw_info.env:/run/arduino_hw_info.env:ro'
      - '/var/sota:/var/sota'
    devices:
      - '/dev/tee0'
