version: '3.6'

services:
  rpi-flask-webserver:
    image: hub.foundries.io/arduino/rpi-flask-webserver:latest
    restart: always
    tty: true
    read_only: false
    environment:
    - BOARD=${BOARD}
    - IS_ON_CARRIER=${IS_ON_CARRIER}
    - CARRIER_NAME=${CARRIER_NAME}
    tmpfs:
    - /run
    - /var/lock
    - /var/log
    - /tmp
    ports:
    - "80:80"
    privileged: true
