name : rpi-flask-webserver

services:

  rpi-flask-webserver:
    image: hub.foundries.io/${FACTORY}/rpi-flask-webserver:latest
    restart: unless-stopped
    environment:
    - BOARD=${BOARD}
    - IS_ON_CARRIER=${IS_ON_CARRIER}
    - CARRIER_NAME=${CARRIER_NAME}
    tmpfs:
    - /run
    - /var/lock
    - /var/log
    - /tmp
    ports:
    - "80:80"
    privileged: true
