version: '3.6'

services:
  mod-ui:
    container_name: mod-ui
    image: aidadsp/mod-ui:3537a24
    restart: unless-stopped
    read_only: false
    user: "0"
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 95
      memlock: -1
    shm_size: 128m
    environment:
      - 'CARD=da7213audio'
      - 'SR=48000'
      - 'BUFFER=1024'
      - 'TTY=ttymxc3'
    ports:
      - '80:8888'
      - '81:8081'
    volumes:
      - '/run/arduino_hw_info.env:/run/arduino_hw_info.env:ro'
      - '/dev/shm:/dev/shm'
    devices:
      - '/dev/snd:/dev/snd'
      - '/dev/ttymxc3:/dev/ttymxc3'
    command: '/entrypoint.sh'

  display:
    container_name: display
    image: hub.foundries.io/${FACTORY}/x-kiosk-imx8:latest
    restart: unless-stopped
    command: "--kiosk --no-first-run --incognito http://mod-ui:8888"
    read_only: true
    shm_size: 128m
    tmpfs:
    - /run
    - /var/lock
    - /var/log
    - /tmp
    volumes:
    - /run/user/63:/run/user/63
    - /dev/dri:/dev/dri
    - /dev/galcore:/dev/galcore
    device_cgroup_rules:
    - 'c 199:* rmw'
    - 'c 226:* rmw'
