version: '3.6'

services:
  go-rpc-proxy:
    image: hub.foundries.io/${FACTORY}/go-rpc-proxy:latest
    restart: always
    tty: true
    read_only: true
    user: "0"
    volumes:
    - "/tmp:/tmp"
    devices:
    - "/dev/x8h7_ui"
    - "/dev/ttyGS0"
    ports:
    - "5000-5100:5000-5100"
