version: '3.6'

services:
  oob-webapp:
    image: hub.foundries.io/arduino/oob-webapp:latest
    restart: always
    user: "63"
    cap_add:
      - NET_ADMIN
    network_mode: "host"
    ports:
      - "1323:1323"
    environment:
      - 'DBUS_SYSTEM_BUS_ADDRESS=unix:path=/run/dbus/system_bus_socket'
    tmpfs:
      - /run
      - /var/lock
      - /var/log
      - /tmp
    volumes:
      - /run/dbus:/run/dbus
