name: x-kiosk

services:

  kiosk:
    image: hub.foundries.io/${FACTORY}/x-kiosk:latest
    restart: unless-stopped
    environment:
    - ADDRESS=www.arduino.cc
    command: "${ADDRESS}"
    read_only: true
    user: "63"
    tmpfs:
    - /run
    - /var/lock
    - /var/log
    - /tmp
    volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix
