version: '3.6'

services:
  xkiosk:
    image: hub.foundries.io/${FACTORY}/x-kiosk:latest
    restart: always
    tty: true
    command: "${ADDR-www.arduino.cc}"
    read_only: true
    user: "63"
    tmpfs:
    - /run
    - /var/lock
    - /var/log
    - /tmp
    volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix
