version: '3.6'

services:
  arduino-iot-cloud-poc:
    container_name: x8-iot-cloud-poc
    image: hub.foundries.io/${FACTORY}/arduino-iot-cloud-poc:latest
    restart: always
    tty: true
    read_only: false
    user: "0"
    environment:
      - 'DBUS_SYSTEM_BUS_ADDRESS=unix:path=/run/dbus/system_bus_socket'
    volumes:
      - '/run/dbus/system_bus_socket:/run/dbus/system_bus_socket'
      - '/run/arduino_hw_info.env:/run/arduino_hw_info.env:ro'
    devices:
      - '/dev/tee0'
